[colors.cursor]
cursor = "#a151d3"

[cursor]
style = "Beam"
thickness = 0.27
unfocused_hollow = false

[font]
size = 14

[font.bold]
family = "UbuntuMono Nerd Font"

[font.italic]
family = "UbuntuMono Nerd Font"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
decorations = "None"
opacity = 0.80

[window.padding]
x = 2
y = 2
